server:
  port: 8815
spring:
  application:
    name: rabbit-forward-service
  rabbitmq:
    addresses: amqp://admin:admin@localhost:5672 # адрес кролика, где загрузочные данные
    listener:
      simple:
        acknowledge-mode: auto
        prefetch: 1
    consumer:
      config:
        queue-name: default  #название очереди, с которой читаем
        exchange-name: default #нахвание обменника
        key: routingKey
    producer:
      config:
        forward-exchange: example #exchange - куда перенаправляем
        addresses: amqp://admin:admin@localhost:5673 #адрес нашего кролика, с которого считываем

